### ISSUE TITLE
Can't run tests (installed with npm and run with ts-node)

### ISSUE THREAD

**Issue by queirozfcom** [Steve-Fenton/tsUnit#27]
After installing the library using npm (`npm install tsunit.external`) and writing a dummy test class like this (`QueryHelperTest.ts`)

```
import * as tsUnit from './../node_modules/tsunit.external/tsUnit';
import * as queryHelper from './../src/app/storedash/helpers/QueryHelper.ts';

export class QueryHelperTest extends tsUnit.TestClass {

    badlyFormedQueryThrowsError() {
        this.areIdentical(1,1);
    }

};
```

and a runner script like this (`tests.ts`)

```
import * as tsUnit from './../../node_modules/tsunit.external/tsUnit';
import {QueryHelperTest} from './../QueryHelperTest';

let tap = new tsUnit.Test(QueryHelperTest).run().getTapResults();

console.log(tap);
```

and then running the script individually using `ts-node`, I get an error message:

```
felipe@felipe-VirtualBox:~/storedash-ui$ ts-node test/runner/tests.ts
SyntaxError: Unexpected token export
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Module._extensions..js (module.js:422:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:304:16)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/felipe/storedash-ui/test/runner/tests.ts:1:19)
    at Module._compile (module.js:413:34)
```

Is there anything obviously wrong here? Thanks

**Comment by Steve-Fenton** [comment]
It looks like you are running the .ts file, rather than the compiled .js file - run tests.js and you should get past the unexpected token error.
